### ISSUE TITLE
Fails to compile with GHC 8.6.3

### ISSUE THREAD

**Issue by jrp2014** [w0rp/ale#2203]
## Information

**VIM version**

N/A

Operating System: MacOS Mohave

## What went wrong

Something went wrong in specifically this place, and I also searched through both open and closed issues for the same problem before reporting a bug here.

Are you having trouble configuring ALE? Try asking for help on [Stack Exchange](https://vi.stackexchange.com/) or perhaps on [Reddit](https://www.reddit.com/r/vim/) instead. The GitHub issue tracker should be used for reporting bugs or asking for new features.

## Reproducing the bug

1. cabal new-install hdevtools
2. Results in this output:
`
:
[ 4 of 14] Compiling Info             ( src/Info.hs, dist/build/hdevtools/hdevtools-tmp/Info.o )

src/Info.hs:215:67: error:
    Not in scope: type constructor or class ‘GHC.PostTc’
    Module ‘GHC’ does not export ‘PostTc’.
    |
215 |         postTcType = const (stage<TypeChecker)                 :: GHC.PostTc TypecheckI GHC.Type -> Bool
    |                                                                   ^^^^^^^^^^
`

### :ALEInfo

N/A
